/**
 * Deterministic analyte-name normalization (CLAUDE.md rule 7).
 *
 * This table is hand-written and version-controlled. It is NEVER generated by a
 * model, and the model is never asked "what is the canonical name for X" — that
 * would reintroduce hallucination into a problem that a lookup solves exactly.
 *
 * An unrecognised name is returned UNCHANGED with `normalized: false`. Guessing at a
 * canonical name we do not know would silently merge two different analytes, which is
 * worse than leaving the raw name visible.
 */

/**
 * alias → canonical name. Keys are matched case-insensitively after punctuation and
 * whitespace are folded, so "Hb", "HB", "hb." and "H B" all resolve identically.
 */
const ALIASES: Readonly<Record<string, string>> = {
  // Haematology
  hb: 'Hemoglobin',
  hgb: 'Hemoglobin',
  haemoglobin: 'Hemoglobin',
  hemoglobin: 'Hemoglobin',
  wbc: 'White Blood Cell Count',
  tlc: 'White Blood Cell Count',
  totalleukocytecount: 'White Blood Cell Count',
  leukocytecount: 'White Blood Cell Count',
  whitebloodcellcount: 'White Blood Cell Count',
  rbc: 'Red Blood Cell Count',
  redbloodcellcount: 'Red Blood Cell Count',
  erythrocytecount: 'Red Blood Cell Count',
  plt: 'Platelet Count',
  plateletcount: 'Platelet Count',
  thrombocytecount: 'Platelet Count',
  hct: 'Hematocrit',
  pcv: 'Hematocrit',
  packedcellvolume: 'Hematocrit',
  haematocrit: 'Hematocrit',
  hematocrit: 'Hematocrit',
  mcv: 'Mean Corpuscular Volume',
  meancorpuscularvolume: 'Mean Corpuscular Volume',
  mch: 'Mean Corpuscular Hemoglobin',
  mchc: 'Mean Corpuscular Hemoglobin Concentration',
  esr: 'Erythrocyte Sedimentation Rate',
  erythrocytesedimentationrate: 'Erythrocyte Sedimentation Rate',

  // Metabolic / chemistry
  fbs: 'Fasting Blood Glucose',
  fastingbloodsugar: 'Fasting Blood Glucose',
  fastingbloodglucose: 'Fasting Blood Glucose',
  fastingplasmaglucose: 'Fasting Blood Glucose',
  ppbs: 'Postprandial Blood Glucose',
  postprandialbloodsugar: 'Postprandial Blood Glucose',
  rbs: 'Random Blood Glucose',
  randombloodsugar: 'Random Blood Glucose',
  hba1c: 'Glycated Hemoglobin (HbA1c)',
  glycatedhemoglobin: 'Glycated Hemoglobin (HbA1c)',
  glycosylatedhemoglobin: 'Glycated Hemoglobin (HbA1c)',
  creatinine: 'Serum Creatinine',
  serumcreatinine: 'Serum Creatinine',
  urea: 'Blood Urea',
  bloodurea: 'Blood Urea',
  bun: 'Blood Urea Nitrogen',
  bloodureanitrogen: 'Blood Urea Nitrogen',
  uricacid: 'Uric Acid',
  serumuricacid: 'Uric Acid',

  // Lipids
  totalcholesterol: 'Total Cholesterol',
  cholesterol: 'Total Cholesterol',
  cholesteroltotal: 'Total Cholesterol',
  hdl: 'HDL Cholesterol',
  hdlcholesterol: 'HDL Cholesterol',
  ldl: 'LDL Cholesterol',
  ldlcholesterol: 'LDL Cholesterol',
  vldl: 'VLDL Cholesterol',
  tg: 'Triglycerides',
  triglycerides: 'Triglycerides',
  triglyceride: 'Triglycerides',

  // Liver
  sgpt: 'Alanine Aminotransferase (ALT)',
  alt: 'Alanine Aminotransferase (ALT)',
  alaninetransaminase: 'Alanine Aminotransferase (ALT)',
  sgot: 'Aspartate Aminotransferase (AST)',
  ast: 'Aspartate Aminotransferase (AST)',
  aspartatetransaminase: 'Aspartate Aminotransferase (AST)',
  alp: 'Alkaline Phosphatase',
  alkalinephosphatase: 'Alkaline Phosphatase',
  ggt: 'Gamma-Glutamyl Transferase',
  totalbilirubin: 'Total Bilirubin',
  bilirubintotal: 'Total Bilirubin',
  albumin: 'Serum Albumin',
  serumalbumin: 'Serum Albumin',

  // Thyroid
  tsh: 'Thyroid Stimulating Hormone (TSH)',
  thyroidstimulatinghormone: 'Thyroid Stimulating Hormone (TSH)',
  t3: 'Triiodothyronine (T3)',
  triiodothyronine: 'Triiodothyronine (T3)',
  t4: 'Thyroxine (T4)',
  thyroxine: 'Thyroxine (T4)',
  ft4: 'Free Thyroxine (FT4)',
  freet4: 'Free Thyroxine (FT4)',

  // Electrolytes and vitamins
  na: 'Sodium',
  sodium: 'Sodium',
  k: 'Potassium',
  potassium: 'Potassium',
  cl: 'Chloride',
  chloride: 'Chloride',
  ca: 'Calcium',
  calcium: 'Calcium',
  serumcalcium: 'Calcium',
  vitamind: 'Vitamin D (25-OH)',
  vitamind3: 'Vitamin D (25-OH)',
  '25ohvitamind': 'Vitamin D (25-OH)',
  vitaminb12: 'Vitamin B12',
  b12: 'Vitamin B12',
  ferritin: 'Ferritin',
  serumferritin: 'Ferritin',
  crp: 'C-Reactive Protein',
  creactiveprotein: 'C-Reactive Protein',
};

export interface NormalizationResult {
  /** The name as it appeared in the source, unchanged. */
  raw: string;
  /** The canonical name, or `raw` verbatim when the alias table has no entry. */
  canonical: string;
  /** True only when the table produced the canonical name. */
  normalized: boolean;
}

/**
 * Fold a name to a lookup key: lowercase, with whitespace and punctuation removed.
 * "Total Cholesterol", "total-cholesterol" and "TOTAL CHOLESTEROL" share a key.
 */
export function toLookupKey(name: string): string {
  return name.toLowerCase().replace(/[\s.\-_/(),:]/g, '');
}

/**
 * Resolve an analyte name to its canonical form.
 *
 * Unknown names are returned unchanged with `normalized: false` — never guessed at.
 */
export function normalizeAnalyteName(rawName: string): NormalizationResult {
  const raw = rawName.trim();
  const canonical = ALIASES[toLookupKey(raw)];

  if (canonical === undefined) {
    return { raw, canonical: raw, normalized: false };
  }

  return { raw, canonical, normalized: true };
}

/** Every canonical name the table can produce. Useful for tests and for the UI. */
export function knownCanonicalNames(): readonly string[] {
  return [...new Set(Object.values(ALIASES))].sort();
}

/** Number of aliases in the table. */
export function aliasCount(): number {
  return Object.keys(ALIASES).length;
}
