import type { ReactElement } from 'react';

import type { ClarificationQuestion } from '@/lib/clarify/questions';

/**
 * Clarification questions.
 *
 * Every item is a QUESTION about missing information, generated by deterministic gap rules
 * in `lib/clarify/questions.ts`. None of it is advice, and the test
 * `contains no advice, urgency or clinical judgement language` enforces that at the source.
 */
export function QuestionsSection({
  questions,
}: {
  questions: readonly ClarificationQuestion[];
}): ReactElement | null {
  if (questions.length === 0) return null;

  return (
    <section
      aria-labelledby="questions-heading"
      className="rounded-lg border border-slate-200 bg-white p-5"
    >
      <h2 id="questions-heading" className="text-lg font-semibold text-slate-900">
        Questions that would improve this record
      </h2>
      <p className="mt-2 max-w-prose text-sm text-slate-600">
        Information that is missing. Answering these makes the record more complete — none of
        it is a prompt to act.
      </p>

      <ol className="mt-3 flex flex-col gap-3">
        {questions.map((question) => (
          <li key={`${question.code}-${question.path}`} className="flex flex-col gap-0.5">
            <p className="font-medium text-slate-900">{question.question}</p>
            <p className="text-sm text-slate-600">{question.reason}</p>
          </li>
        ))}
      </ol>
    </section>
  );
}
